name: Build and Release APK

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'fastlane/**'
      - 'assets/**'
      - '.github/**/*.md'
      - '.github/FUNDING.yml'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      - name: Build release APK
        run: ./gradlew assembleRelease --no-daemon --console=plain

      - name: Sign APK
        run: |
          # Example of signing the APK with your keystore
          # Replace with your keystore information and passwords
          echo "Signing APK..."
          keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-key-alias
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore my-release-key.jks app/build/outputs/apk/release/app-release-unsigned.apk my-key-alias

      - name: Zip align APK
        run: |
          # Example of zip aligning the APK
          # Replace with your APK path
          echo "Zip aligning APK..."
          $ANDROID_HOME/build-tools/32.0.0/zipalign -v 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
